wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695096717.835504
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.9.17
      5: 0.15.8
      8:
      - 5
model:
  desc: null
  value: detr
batch_size:
  desc: null
  value: 4
etc:
  desc: null
  value: etc
